# Stochastic

In the beginning of the modern era of finance, mainly in the 1970s and 1980s, the major goal of financial research was to come up with closed-form solutions, for, e.g., option prices given a specific financial model. The requirements have drastically changed in recent years in that not only is the correct valuation of single financial instuments important to participants in the financial markets, but also the consistent valuation of whole derivatives books. To come up with risk measures across a whole financial institution, like value-at-risk and credit valuation adjustments, one needs to take into account the whole book of the institution and all its counterparty.

## Random Numbers

In [1]:
# import packages

import math
import numpy as np
import numpy.random as npr      # import the random number generation subpackage from NumPy
from pylab import plt, mpl
import seaborn as sns

sns.set()
mpl.rcParams['font.family'] = 'serif'

%matplotlib inline

The `rand()` function returns random numbers from the open interval [0, 1) in the shape provided as a parameter to the function. The return pbject is an ndarray object.

In [2]:
# if one wants to generate from numbers from the interval [a, b)=[5, 10), one can transform the returned numbers from npr.rand()

npr.seed(100)           # Fixes the seed value for reproducibility
np.set_printoptions(precision=4) 

npr.rand(10)            # Uniformly distributed random numbers as one-dimensional ndarray object


array([0.5434, 0.2784, 0.4245, 0.8448, 0.0047, 0.1216, 0.6707, 0.8259,
       0.1367, 0.5751])

In [3]:
npr.rand(5, 5)      # Uniformly distributed random numbers as two-dimensional ndarray object

array([[0.8913, 0.2092, 0.1853, 0.1084, 0.2197],
       [0.9786, 0.8117, 0.1719, 0.8162, 0.2741],
       [0.4317, 0.94  , 0.8176, 0.3361, 0.1754],
       [0.3728, 0.0057, 0.2524, 0.7957, 0.0153],
       [0.5988, 0.6038, 0.1051, 0.3819, 0.0365]])

In [4]:
a = 5.          # lower limit
b = 10.         # and upper limit

In [5]:
npr.rand(10) * (b - a) + a      # for the transformation to another interval

array([9.4521, 9.9046, 5.2997, 9.4527, 7.8845, 8.7124, 8.1509, 7.9092,
       5.1022, 6.0501])

In [6]:
npr.rand(5, 5) * (b - a) + a    # the same transformation for two dimensions

array([[7.7234, 8.8456, 6.2535, 6.4295, 9.262 ],
       [9.875 , 9.4243, 6.7975, 7.9943, 6.774 ],
       [6.701 , 5.8904, 6.1885, 5.2243, 7.5272],
       [6.8813, 7.964 , 8.1497, 5.713 , 9.6692],
       [9.7319, 8.0115, 6.9388, 6.8159, 6.0217]])

<b>Functions for single random number generation</b>
<table>
<tr>
    <th>Functions</th>
    <th>Parameters</th>
    <th>Returns/result</th>
</tr>
<tr>
    <td> rand </td>
    <td>d1, d1, ..., dn</td>
    <td>Random values in the given shape</td>
</tr>
</table>