In [1]:
import ptan
import torch.nn as nn 

In [2]:
class DQNet(nn.Module):
    def __init__(self):
        super(DQNet, self).__init__()
        self.ff = nn.Linear(5, 3)
        
    def forward(self, x):
        return self.ff(x)

In [3]:
net = DQNet()
print(net)

DQNet(
  (ff): Linear(in_features=5, out_features=3, bias=True)
)


In [4]:
tgt_net = ptan.agent.TargetNet(net)
print("Main net: ", net.ff.weight)
print("Target net: ", tgt_net.target_model.ff.weight)

Main net:  Parameter containing:
tensor([[-0.2375, -0.2449,  0.0261, -0.0728, -0.1697],
        [ 0.1646, -0.0012, -0.2152, -0.0312, -0.2268],
        [ 0.2500, -0.0504, -0.1340, -0.0713, -0.1476]], requires_grad=True)
Target net:  Parameter containing:
tensor([[-0.2375, -0.2449,  0.0261, -0.0728, -0.1697],
        [ 0.1646, -0.0012, -0.2152, -0.0312, -0.2268],
        [ 0.2500, -0.0504, -0.1340, -0.0713, -0.1476]], requires_grad=True)


In [5]:
net.ff.weight.data += 1.0
print("after update")
print("main net: ", net.ff.weight)
print("target net: ", tgt_net.target_model.ff.weight)

after update
main net:  Parameter containing:
tensor([[0.7625, 0.7551, 1.0261, 0.9272, 0.8303],
        [1.1646, 0.9988, 0.7848, 0.9688, 0.7732],
        [1.2500, 0.9496, 0.8660, 0.9287, 0.8524]], requires_grad=True)
target net:  Parameter containing:
tensor([[-0.2375, -0.2449,  0.0261, -0.0728, -0.1697],
        [ 0.1646, -0.0012, -0.2152, -0.0312, -0.2268],
        [ 0.2500, -0.0504, -0.1340, -0.0713, -0.1476]], requires_grad=True)


In [6]:
tgt_net.sync()
print("after sync")
print("main net: ", net.ff.weight)
print("target net: ", tgt_net.target_model.ff.weight)

after sync
main net:  Parameter containing:
tensor([[0.7625, 0.7551, 1.0261, 0.9272, 0.8303],
        [1.1646, 0.9988, 0.7848, 0.9688, 0.7732],
        [1.2500, 0.9496, 0.8660, 0.9287, 0.8524]], requires_grad=True)
target net:  Parameter containing:
tensor([[0.7625, 0.7551, 1.0261, 0.9272, 0.8303],
        [1.1646, 0.9988, 0.7848, 0.9688, 0.7732],
        [1.2500, 0.9496, 0.8660, 0.9287, 0.8524]], requires_grad=True)
