In [2]:
import torch
import numpy as np

torch.cuda.is_available()

True

# Create a tensor

In [3]:
# create a tensor

a = torch.FloatTensor(3, 2)
a

tensor([[2.0316e+20, 3.2918e-09],
        [2.1273e+23, 1.0606e-08],
        [1.7012e-04, 2.1363e-07]])

In [4]:
# initialize with zeros
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
# another way to create a tensor by its constructor is to provide a Python iterable (i.e., a list or tuple)
torch.FloatTensor([[1, 2, 3], [3, 2, 1]])

tensor([[1., 2., 3.],
        [3., 2., 1.]])

In [6]:
# create the same tensor with zeros using NumPy
n = np.zeros(shape=(3, 2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
b = torch.tensor(n)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [9]:
# common practice is to use the 32-bit floar type
n = np.zeros(shape=(3, 2), dtype=np.float32)
torch.tensor(n)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [11]:
# the type of the desired tensor could be provided to the torch.tensor
n = np.zeros(shape=(3, 2))
torch.tensor(n, dtype=torch.float32)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

# Scalar tensor

In [12]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [13]:
s = a.sum()
s

tensor(6)

In [14]:
s.item()

6

In [15]:
torch.tensor(1)

tensor(1)

# GPU tensors

In [16]:
a = torch.FloatTensor([2, 3])
a

tensor([2., 3.])

In [18]:
ca = a.to('cuda')
ca

tensor([2., 3.], device='cuda:0')

In [22]:
print(a + 1)
print(ca + 1)

tensor([3., 4.])
tensor([3., 4.], device='cuda:0')


In [23]:
ca.device

device(type='cuda', index=0)