# 데이터분석 단계 (Data Analysis Cycle)

<img src='./img/DataAnalysis_Cycle0.png'>

<br>

<img src='./img/DataAnalysis_Cycle1.png'>

<br>

<img src='./img/DataAnalysis_Cycle2.png'>

<br>

<img src='./img/DataAnalysis_Cycle3.png'>

<br>

<img src='./img/DataAnalysis_Cycle4.png'>

<br>

<img src='./img/DataAnalysis_Cycle5.png'>

<br>

<img src='./img/DataAnalysis_Cycle6.png'>

<br>

<img src='./img/DataAnalysis_Cycle7.png'>

<br>

<img src='./img/DataAnalysis_Cycle8.png'>

<br>

<img src='./img/DataAnalysis_Cycle9.png'>


# 시계열분석과 기계학습의 차이 (Comparison)

## 확률적 프로세스 및 시계열 데이터

<img src='./img/TS_MS_Comparison.png'>

- **확률적 프로세스(Stochastic Process)** : 시간에 따라 확률적 수치의 변화를 가지는 함수

    - **변수**

    $$X={X_1, X_2, ..., X_n}$$

    - **확률적 프로세스** : 각 변수 내 확률적 수치의 변화

    $$Y={..., Y_{-2}, Y_{-1}, Y_0, Y_1, Y_2, ...}, X_1={..., X_{1, -2}, X_{1, -1}, X_{1, 0}, X_{1, 1}, X_{1, 2}, ...}, X_2={..., X_{2, -2}, X_{2, -1}, X_{2, 0}, X_{2, 1}, X_{2, 2}, ...}, ...$$

    - 종속변수($Y_t$) 또는 독립변수($X_{1, t}$)가 시간단위($t$)를 포함

    - 모델링읜 출력(Output)은 변수 $Y$의 특정 시간 $t$에서의 예측값 ($\hat{Y}_t$)

- **시계열 데이터(Time Series Data)** : 일정한 시간 간격에 따라 순차적(Sequentially)으로 기록된 확률적 프로세스 또는 시간변화 데이터

    - 시간의 흐름에 따라 불규칙적 변동을 분석하기 위해 필수적 데이터

    - 과거가 미래에 어떤 영향을 주는 지 분석을 통해 예측 가능

    - 최근 기계학습과 딥러닝을 사용하여 복잡한 데이터 예측

    - 시계열예측과 기계학습/딥러닝 간 전처리와 알고리즘 방식 차이 때문에 별도로 (1) 시계열 데이터분석 단계 이해, (2) 시계열 데이터의 전처리, (3) 시계열 알고리즘 이해 필수!

<img src='./img/TS_Example1.png'>

<br>

<img src='./img/TS_Example2.png'>

## 시계열 데이터의 활용

- 관측된 시계열 데이터를 분석하여 미래를 예측하는 문제가 바로 시계열 예측 문제

- 흔하게 접하는 문제로 주로 경제 지표를 예측하거나 시간에 따른 정당지지율을 예측하거나, 어떤 상품의 수요를 예측하는 문제에 이르기까지 다양하게 활용되고 있으며 현실에 가까울수록 항상 고려해야 하는 문제

<img src='./img/TS_Applications.png'>

- 예측된 결과를 바탕으로 여러 정책이나 비즈니스 전략을 결정하는 과정에 활용되기에, 실제 비즈니스 영역에서는 시계열 예측 문제가 매우 중요

<img src='./img/DataUseCase.png'>

- McKinsey Global Institute에 따르면, 시계열 데이터가 텍스트나 이미지 데이터 보다 더 큰 잠재적 가치를 가지고 있다고 보고있음

<img src='./img/DataPotential.png'>

## 데이터분석 단계의 변화

**"시계열예측과 기계학습/딥러닝 간 전처리와 알고리즘 방식 차이 때문에, 별도로 (1) 시계열 데이터분석 단계 이해, (2) 시계열 데이터의 전처리, (3) 시계열 알고리즘 이해 필수!"**

<img src='./img/DataAnalysis_CycleTS0.png'>

<br>

<img src='./img/DataAnalysis_Cycle1.png'>

<br>

<img src='./img/DataAnalysis_CycleTS1.png'>

<br>

<img src='./img/DataAnalysis_CycleTS2.png'>

<br>

<img src='./img/DataAnalysis_CycleTS5.png'>

### [시계열 알고리즘 종류](https://paperswithcode.com/area/time-series)

- 통계추론, 기계학습 및 딥러닝의 흐름에 시간패턴을 반영하려 진화

- 지도학습(예측 분류), 비지도학습 문제에 모두 활용되는 필수 알고리즘

- 미래 예측을 포함한 추천 서비스와 같은 비즈니스에 활용중

<img src='./img/TS_Evolution.png'>

#### 1) 통계추론(Statistical Inference) 알고리즘: 통계분포에 기반한 설명력 중시 알고리즘

<img src='./img/TS_Algorithm_Concept.png'>

**(1) 단변량 선형기반**: Y가 1개 & Y와 X의 관계를 선형 가정

- Linear Regression

- ARIMA(AutoRegressive Integrated Moving Average)

- ARIMAX

- SARIMAX

**(2) 다변량 선형기반**: Y가 2개 이상 & Y와 X의 관계를 선형 가정

- Bayesian-based Models

- Vector Autoregression(VAR)

- Vector Error Correction Model(VECM)

**(3) 비선형기반**: Y와 X의 관계를 비선형 가정

- Exponential Smoothing

- ETS(Error/Trend/Seasonal)

- Kalman Filter

- State Space Model

- Change Point Detection(CPD)

- Autoregressive conditional heteroskedasticity(ARCH)

- Generalized Autoregressive Conditional Heteroskedasticity(GARCH)

#### 2) 기계학습/딥러닝 알고리즘: 컴퓨팅 기반 인공지능 알고리즘으로 정확성 높은 비선형 관계 추론

- Prophet

- Neural Prophet

- RNN(Recurrent Neural Network)

- LSTM(Long Short-Term Memory)

- GRU(Gated Recurrent Unit)

- Neural Networks Autoregression(NNAR)

- Attention

- Self-attention

- Transformer

#### 3) Platforms: 글로벌 기업들이 독자적으로 개발한 시계열 분석 플랫폼 확대중

- [Amazon Forecast](https://aws.amazon.com/ko/forecast/)

- [Automated ML Time-series Forecasting at Microsoft Azure](https://azure.microsoft.com/en-us/blog/build-more-accurate-forecasts-with-new-capabilities-in-automated-machine-learning/)

- [Time Series Forecasting with Google Cloud AI Platform](https://codelabs.developers.google.com/codelabs/time-series-forecasting-with-cloud-ai-platform#0)

# 전처리 방향 (Preprcessing)

**"시계열예측과 기계학습/딥러닝 간 전처리와 알고리즘 방식 차이 때문에, 별도로 (1) 시계열 데이터분석 단계 이해, (2) 시계열 데이터의 전처리, (3) 시계열 알고리즘 이해 필수!"**

- **목표**

    - 대량으로 수집된 데이터는 그대로 활용 어려움

    - 잘못 수집/처리 된 데이터는 엉뚱한 결과를 발생

    - 알고리즘이 학습이 가능한 형태로 데이터를 정리

<img src='./img/DataAnalysis_Time.jpg' width=500>

- **일반적인 전처리 필요항목**

    - 데이터 결합

    - 결측값 처리

    - 이상치 처리

    - 자료형 변환

    - 데이터 분리

    - 데이터 변환

    - 스케일 조정

$\Rightarrow$ **"알고리즘의 범위와 종류가 다양하여, 각 알고리즘의 입력에 맞게 변환하는 것이 최선"**

## 시계열 변수추출 (Feature Engineering)

- 데이터 과학자들은 보통 수동/자동 변수 처리 및 변환(Feature Engineering)에 익숙하지만, 새로운 변수를 생성하는 것은 분석에서 가장 중요하고 시간이 많이 걸리는 작업 중 하나이며, 머신러닝과 딥러닝의 발전으로 점차 자동화 중

<img src='./img/DL_AutoFE.png'>

- **변수 생성시 주의할 점!**

    - 미래의 실제 종속변수 예측값이 어떤 독립/종속변수의 Feature Engineering에 의해 효과가 있을지 단정할 수 없음

    - 독립변수의 예측값을 Feature Engineering를 통해 생성될 수 있지만 이는 종속변수의 예측에 오류증가를 야기할 수 있음

### 구성요소 및 시간빈도

#### 1) 시계열 데이터는 여러 구성 성분

- **시계열 = 체계적 성분 + 불규칙 성분**

<img src='./img/TimeSeries_Decomposition.png' width=500>

| 시계열 방향 | 시계열 구성요소 | 의미 | 
|:---: |:--- |:--- | 
| 장기적 움직임 | 추세(Trend) | 장기적으로 시간흐름에 따른 데이터의 상승/하강 경향 | 
| 단기적 움직임 | 계절성(Seasonality) | 특정기간 간격으로 반복적으로 나타나는 패턴 <br> 주기(Cycle) | 계절변동으로 설명되지 않는 패턴(기후변화, 정책변화, 사회관습 등) | 
| 불규칙 움직임 | 에러(Error) | 사전(Prior)적으로 예측할 수 없는 특수 패턴(지진, 전쟁, 파업 등) |

#### 2) 여러 구성성분들이 단기적 및 장기적으로 복합적으로 융합되어 작동

<img src='./img/TS_Example3.png' width=600>

#### 3)  빈도(Frequency): 사람이 인지하는 데이터의 빈도를 컴퓨터는 명확히 인지하지 못하기 때문에 별도 설정필요

- **계절성 패턴(Seasonality)**이 나타나기 전까지의 데이터 갯수로 분석가가 반영

    - 예시 1

    | Data | Seasonality | Frequency |
    |:---:|:---:|:---:| 
    | Annual | Annual | 1 | 
    | Quarterly | Annual | 4 | 
    | Monthly | Annual | 12 | 
    | Weekly | Annual | 52 |

    - 예시 2

    | Data | Seasonality | Frequency |
    |:---:|:---:|:---:| 
    | Daily(데이터가 Day 단위로 수집) | Weekly | 7 | 
    | | Annual | 365 |

    - 예시 3

    | Data | Seasonality | Frequency |
    |:---:|:---:|:---:| 
    | Minutely(데이터가 Minute 단위로 수집) | Hourly | 60 | 
    | | Daily | 24 x 60 |
    | | Weekly | 24 x 60 x 7 | 
    | | Annual | 24 x 60 x 365 |
    

- **빈도 설정을 위한 Python 함수 옵션**

    | **Alias** | **Description** |
    |:---:|:---:|
    | **B** | Business day |
    | **D** | Calendar day |
    | **W** | Weekly |
    | **M** | Month end |
    | **Q** | Quaterly end |
    | **A** | Year end |
    | **BA** | Business year end |
    | **AS** | Year start |
    | **H** | Hourly frequency |
    | **T, min** | Minutely frequency |
    | **S** | Secondly frequency |
    | **L, ms** | Millisecond frequency |
    | **U, us** | Microsecond frequency |
    | **N, ns** | Nanosecond frequency |

- 빈도 설정 후 비어있는 시간 결측치가 발견되거나 빈도 변경으로 발생하는 **결측치를 채우기 위한 Python 함수 옵션**

    - 시계열에는 노이즈 데이터 또는 관찰되지 못한 기간이 종종 존재
    
    - 측정하고 데이터를 기록하는 과정에서의 오류나 예측치 못한 상황으로 인해 발생
    
    - 예를들어 상품의 품절로 인하여 장기간 판매량이 없는 경우 데이터는 없을 수 있고 이를 적절하게 전처리 하는 것이 실제 문제해결 성능에 매우 중요

    | **Method** | **Description** |
    |:---:|:---:|
    | **bfill** | Backeard fill |
    | **count** | Count of values |
    | **ffill** | Forward fill |
    | **first** | First valid data value |
    | **last** | Last valid data value |
    | **max** | Maximum data value |
    | **mean** | Mean of values in time range |
    | **median** | Median of values in time range |
    | **min** | Minimum data value |
    | **nunique** | Number of unique values |
    | **ohlc** | Opening value, highest value, lowest value, closing value |
    | **pad** | Same as forward fill |
    | **std** | Standard deviation of values |
    | **sum** | Sum of values |
    | **var** | Variance of values |


### 추세/계절성/주기/지연값 등

#### 1) 추세(Trend, $T_t$)

- 시계열이 시간에 따라 증가, 감소 또는 일정 수준을 유지하는 경우

**(시각적 이해)**

<img src='./img/Trend_Increasing.png' width=500>

<img src='./img/Trend_Decreasing.png' width=500>

<img src='./img/Trend_None.png' width=500>

**(수학적 이해)**

- 확률과정의 기댓값 함수를 알아내는 것

- 확률과정($Y_t$)이 추정이 가능한 추세함수($f(t)$)와 정상확률과정($Y_t^s$)의 합

$$Y_t=f(t)+Y_t^s$$

#### 2) 계절성(Seasonality, $S_t$)

- 일정한 빈도로 주기적으로 반복되는 패턴($m$), 특정한 시간값(달/요일)에 따라 기대값이 달라지는 것

- **예시** : 주기적 패턴이 12개월마다 반복($m=12$)

<img src='./img/Seasonal.png' width=500>

- **대표적 계절성 변수 생성 2가지**

    - 수치값 그대로 반영 $\rightarrow$ `LabelEncoding`

        <img src='./img/Label_Encoding.png' width=300>

    - 계절성 주기 내 시점마다 별도 변수 생성 $\rightarrow$ `OneHotEncoding`

        <img src='./img/Dummy_Engineering.png' width=500>

#### 3) 주기(Cycle, $C_t$)

- 일정하지 않은 빈도로 발생하는 패턴(계절성과 다름)

- 예시: 빈도가 1인 경우에도 발생 가능($m=1$)

<img src='./img/Cycle.png' width=400>

#### 4) 시계열 분해(추세/계절성/잔차(Residual, $e_t$))

<img src='./img/Decomposed_into_its_trend_seasonal_and_irregular.jpeg' width=600>

**(1) 가법모형(Additive Model)**: 추세 + 계절성 + 주기 + 오차

- 구성요소간 독립성을 가정하고 시계열이 구성요소의 합 가정

- 주로 계절성분의 진폭/분산이 시간이 흘러도 일정한 경우 사용

**(2) 승법모형(Multiplicative Model)**: 추세 * 계절성 * 주기 * 오차

- 구성요소간 비독립성을 가정하고 시계열이 구성요소의 곱 가정

- 주로 계절성분의 진폭/분산이 시간에 따라 일정하지 않은 경우 사용

#### 5) 지연값(Lagged values, $Lag(X_1)$) 

- 변수의 지연된 값들로 별도 독립변수를 생성하는 것으로, ARIMA/VAR/NNAR(Neural Network Autoregression) 등의 알고리즘도 내부적으로 활용

<img src='./img/Lag-explanation.png' width=400>

#### 6) 시간변수 

- 시간정보가 담고 있는 년/월/일/요일 등 자체를 별도 독립적인 변수로 생성

#### 요약

- 시계열 구성요소는 각 변수의 시간패턴을 파악하는데 중요

- FE를 통해 생성된 변수의 입력(Input) 형태나 빈도로 알고리즘 선택시 고려해야

- 생성된 변수의 패턴이 기존 모델에서 반영하지 않던 패턴이라면 예측 성능을 높임

- 예측성능 향상 뿐 아니라 결과를 해석하고 해당 속성을 분석하며 가능한 원인 식별에 도움

## 데이터 분리 (Data Split)

- **배경**

    **(1) 독립변수와 종속변수 구분**

    | 대분류 | 의미/예시 |
    |:---: |:---: | 
    | 독립변수(Independent Variable) | 다른 변수에 영향을 미치는 변수 (X) | 
    | 종속변수(Dependent Variable) | 다른 변수에 의해 영향을 받는 변수 (Y) |

    **(2) 과거/현재와 미래 기간 구분**

    - 과거/현재의 상황을 분석하고, 미래를 예측 할 수 있는 환경 구축

    - **Training Period**: 과거/현재의 상황을 분석

    <img src='./img/DataSplit_Concept1.png'>

    - **Testing Period**: 미래를 예측 할 수 있는 환경

    <img src='./img/DataSplit_Concept2.png'>

#### 1) 간단한 방법(Holdout Validation)

- **훈련셋(Training set)**: 일반적으로 전체 데이터의 70% 사용

- **테스트셋(Testing set)**: 일반적으로 전체 데이터의 30% 사용

#### 2) 일반적 방법(Simple Validation)

- **훈련셋(Training set)**: 일반적으로 전체 데이터의 60%를 사용

- **검증셋(Validation set)**:

    - 개발셋이라고도 하며, 일반적으로 전체 데이터의 20%를 사용함

    - 훈련된 여러가지 모델들의 성능을 테스트 하는데 사용되며 모델 선택의 기준이 됨

- **테스트셋(Testing set)**: 일반적으로 전체 데이터의 20%를 사용하며 최종 모델의 정확성을 확인하는 목적에 사용됨

<img src='./img/DataSplit_Simple.png' width=500>


#### 3) K교차검사 (K-fold cross validation)

(1) 훈련셋을 복원없이 K개로 분리한 후, K-1는 하위훈련셋으로 나머지 1개는 검증셋으로 사용함

(2) 검증셋과 하위훈련셋을 번갈아가면서 K번 반복하여 각 모델별로 K개의 성능 추정치를 계산

(3) K개의 성능 추정치 평균을 최종 모델 성능 기준으로 사용

<img src='./img/DataSplit_Kfold.png' width=500>

#### 4) K-fold vs. Random-subsamples vs. Leave-out vs. Leave-p-out

- **K-fold**

<img src='./img/DataSplit_ver1.png' width=500>

- **Random-subsamples**

<img src='./img/DataSplit_ver3.png' width=500>

- **Leave-p-out**

<img src='./img/DataSplit_ver4.png' width=500>

### 시계열 데이터 분리

#### 1) 시계열 데이터인 경우 랜덤성(set.seed) 없이 시간축 유지가 핵심!

- **훈련셋 < 검증셋 < 테스트셋**

    - **훈련셋(Training set)**: 가장 오래된 데이터

    - **검증셋(Validation set)**: 그 다음 최근 데이터

    - **테스트셋(Testing set)**: 가장 최신의 데이터

    <img src='./img/DataSplit_TimeSeries.png' width=500>

#### 2) 최선의 성능을 가지는 Robust 모델링을 위해 시계열 교차검증 필수!

(1) **모든 미래 시점을 한번에 예측하면 정확성 낮아짐**: 미래 시점마다 Train/Test 재분류 필요

- **Sliding Window**: 고정된 사이즈의 Train & Test Window를 움직이며 데이터를 재분리

- **Expanding Window**: 가변 사이즈 Train Window & 고정된 사이즈 Test Window를 움직이며 데이터를 재분리

<img src='./img/DataSplit_TSWindow.png'>

(2) 단기/중기/장기 모든 미래시점에 동일 성능을 가지는 Robust 알고리즘은 없기 때문에 시점마다 별도 모델링 필요

- **1스텝 교차검사(One-step Ahead Cross-validation)**

<img src='./img/DataSplit_TimeSeries_ver1.png' width=500>

- **2스텝 교차검사(Two-step Ahead Cross-validation)**

<img src='./img/DataSplit_TimeSeries_ver2.png' width=500>


## 데이터 변환 (Realitu & Feature Selection)

### 시간현실 반영 (Reality)

**미래의 시간패턴을 미리 반영하는건 비현실적, 이는 과적합(Overfitting) 유발**

- 데이터 전처리시, 데이터 분리 후 패턴을 추출하여 해결

<img src='./img/DataAnalysis_CycleTS0.png'>

<img src='./img/DataAnalysis_Cycle1.png'>

<img src='./img/DataAnalysis_CycleTS1.png'>

### 변수들의 독립성 향상(Condition Number)

#### 1) 배경: 예측 성능을 향상시키려면 독립변수들의 독립성이 높아야 함

- 이상적: Train 예측성능 $\uparrow$ + Test 예측성능 $\uparrow$

- 현실적: Train 예측성능 <<< Test 예측성능 $\Leftrightarrow$ 낮은 조건수(Condition Number)

#### 2) 낮은 조건수란?

**(비수학적 이해)**

- 독립변수들($X$)의 상호의존도(관련성)가 분석결과($Y$)에 주는 영향을 줄이고, 독립변수 각각의 순수한 영향만을 반영

**(수학적 이해)**

- 독립변수($X$)가 움직일 수 있는 변동성(공분산)을 줄여 분석결과(Y)의 변동을 줄여 신뢰성 향상

- **변동성(공분산)?**: 알고리즘이 예측 영향력(계수/가중치)추정 과정에서 발생하는 역행렬의 변화에 오차가 미치는 영향

$$\text{Condition Number(조건수)}=\frac{\lambda_{max}}{\lambda_{min}}$$

$$\lambda_{max}=\max[\text{eigenvalue}\{Cov(X^TX)\}]$$

$$\lambda_{max}=\min[\text{eigenvalue}\{Cov(X^TX)\}]$$

In [1]:
# 조건수가 작을 때
# X 데이터
import numpy as np
A = np.eye(4)
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
# Y 데이터
Y = np.ones(4)
Y

array([1., 1., 1., 1.])

In [3]:
# 계수 추정
np.linalg.solve(A, Y)

array([1., 1., 1., 1.])

In [4]:
# X 데이터 오차반영
A_new = A + 0.0001 * np.eye(4)
A_new

array([[1.0001, 0.    , 0.    , 0.    ],
       [0.    , 1.0001, 0.    , 0.    ],
       [0.    , 0.    , 1.0001, 0.    ],
       [0.    , 0.    , 0.    , 1.0001]])

In [5]:
# 계수 추정
np.linalg.solve(A_new, Y)

array([0.99990001, 0.99990001, 0.99990001, 0.99990001])

In [6]:
# 조건수 확인
np.linalg.cond(A)

1.0

In [7]:
# 조건수가 클 때
# X 데이터
from scipy.linalg import hilbert
A = hilbert(4)
A

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

In [8]:
# Y 데이터
Y = np.ones(4)
Y

array([1., 1., 1., 1.])

In [9]:
# 계수 추정
np.linalg.solve(A, Y)

array([  -4.,   60., -180.,  140.])

In [10]:
# 데이터 오차 반영
A_new = A + 0.0001 * np.eye(4)
A_new

array([[1.0001    , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33343333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2001    , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14295714]])

In [11]:
# 계수 추정
np.linalg.solve(A_new, Y)

array([ -0.58897672,  21.1225671 , -85.75912499,  78.45650825])

In [12]:
# 조건수 확인
np.linalg.cond(A)

15513.738738929662

#### 3) 조건수를 낮추는 방법: 예측 안정성(Robust/Goodfit)을 높이는 방법

(1) 변수들의 단위차이로 숫자의 스케일들이 크게 다른 경우, 스케일링(Scaling)으로 해결 가능

(2) 독립변수들 간에 상관관계(상호의존성)가 높은 다중공선성 존재할 경우, Variance Inflation Factor(VIF)나 Principal Component Analysis(PCA)를 통한 변수선별로 해결 가능

(3) 독립변수들 간 상호의존성이 높은 변수들에 패널티를 부여하는 정규화(Resularization)로 해결 가능

### 다중공선성(Multicollinearity)

#### 1) 다중공선성(Multicollinearity)이 발생하는 경우

- 특정 독립변수가 다른 독립변수의 조합으로 표현될 수 있는 경우

- 독립변수들이 서로 독립이 아니라 상호상관관계가 강한 경우

- 독립변수의 공분산 행렬(Covariance Matrix) 벡터공간(Vector Space)의 차원과 독립변수의 수가 달라 변수들이 모두 독립이 아닌 경우(Full Rank가 아니다)

$\Rightarrow$ 다중공선성이 있으면 독립변수 공분산 행렬의 조건수(Condition Number) 증가

$\Rightarrow$ 조건수(Condition Number)가 증가하면 과적합(Overfitting) 발생가능성 증가

#### 2) 다중공선성을 줄이는 방법

(1) Variance Inflation Factor(VIF) 변수선택

- VIF는 독립변수를 다른 독립변수들로 선형회귀한 성능들을 비교하여 상호 의존성이 높은 변수를 제거하거나 의존성이 낮은 변수를 선택

$$VIF_i=Var(\hat{\beta}_i)=\frac{\sigma^2}{(n-1)Var(X_i)}\cdot\frac{1}{1-R_i^2}$$

$$(R_i^2\text{ : 독립변수 $X_i$를 다른 독립변수들로 선형회귀한 성능})$$


(2) Principal Component Analysis(PCA) 변수선택

- PCA는 다차원에서 상호 관련성이 높은 독립변수들을 관련성이 없는 서로 독립인 소차원으로 변경하는 알고리즘으로, 이를 통해 상호 의존성을 제거

<img src='./img/PCA_2D_Ex.png'>

<img src='./img/PCA_Visualization.png'>

<img src='./img/PCA_MultiEx.png'>

<img src='./img/PCA_MultiExPC1PC2.png' width=600>



## [스케일 조정(Scaling)](https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html#sphx-glr-download-auto-examples-preprocessing-plot-all-scaling-py)

- **목적**: 변수들의 크기를 일정하게 맞추어 크기 때문에 영향이 높은 현상을 회피

    - **수학적**: 독립 변수의 공분산 행렬 조건수(Condition Number)를 감소시켜 최적화 안정성 및 수렴 속도 향상

    - **컴퓨터적**: PC 메모리를 고려하여 오버플로우(Overflow)나 언더플로우(Underflow)를 줄여줌    

#### 1) Standard Scaler

$$\frac{X_{it}-E(X_i)}{SD(X_i)}$$

- 기본 스케일로 평균을 제외하고 표준편차를 나누어 변환

- 각 변수(Feature)가 정규분포를 따른다는 가정이기에 정규분포가 아닐 시 최선이 아닐 수 있음

```python
sklearn.preprocessing.StandardScaler().fit()
sklearn.preprocessing.StandardScaler().transform()
sklearn.preprocessing.StandardScaler().fit_transform()
```

<img src='./img/Scaling_StandardScaler.png' width=500>

#### 2) Min-Max Scaler

$$\frac{X_{it}-\min(X_i)}{\max(X_i)-\min(X_i)}$$

- 가장 많이 활용되는 방식으로 최소~최대 값이 0~1 또는 -1~1 사이의 값으로 변환

- 각 변수(Feature)가 정규분포가 아니거나 표준편차가 매우 작을 때 효과적

```python
sklearn.preprocessing.MinMaxScaler().fit()
sklearn.preprocessing.MinMaxScaler().transform()
sklearn.preprocessing.MinMaxScaler().fit_transform()
```

<img src='./img/Scaling_MinMaxScaler.png' width=500>

#### 3) Robust Scaler

$$\frac{X_{it}-Q_1(X_i)}{Q_3(X_i)-Q_1(X_i)}$$

- 최소-최대 스케일러와 유사하지만 최소/최대 대신에 IQR(Interquartile Range) 중 25%값/75%값을 사용하여 변환

- 이상치(Outlier)에 영향을 최소화하였기에 이상치가 있는 데이터에 효과적이고 적은 데이터에도 효과적인 편

```python
sklearn.preprocessing.RobustScaler().fit()
sklearn.preprocessing.RobustScaler().transform()
sklearn.preprocessing.RobustScaler().fit_transform()
```

<img src='./img/Scaling_RobustScaler.png' width=500>

#### 4) Normalizer

$$\frac{X_{it}}{\sqrt{X_i^2+X_j^2+...+X_k^2}}$$

- 각 변수(Feature)를 전체 n개 모든 변수들의 크기들로 나누어서 변환(by Cartesian Coordinates)

- 각 변수들의 값은 원점으로부터 반지름 1만큼 떨어진 범위 내로 변환

```python
sklearn.preprocessing.Normalizer().fit()
sklearn.preprocessing.Normalizer().transform()
sklearn.preprocessing.Normalizer().fit_transform()
```

<img src='./img/Scaling_Normalizer.png' width=500>

## 모델링 방향 (Modeling)

시계열예측과 기계학습/딥러닝 간 전처리와 알고리즘 방식 차이 때문에, 별도로 (1) 시계열 데이터분석 단계 이해, (2) 시계열 데이터의 전처리, (3) 시계열 알고리즘 이해 필수!

### 시계열 알고리즘의 특징과 종류

(1) 학습된 데이터 범위 내 패턴 뿐 아니라 외부 순차적 시점들의 패턴으로도 확장 할 수 있어야 시계열 알고리즘

- 대다수의 기계학습 알고리즘은 데이터 범위 내 패턴만을 추출

- 시계열 데이터나 FE를 통해 생성된 변수들은 미래시점의 패턴으로도 확장시킬 수 있음

(2) 시계열 알고리즘은 특정시점(점추정)이 아닌 특정시점의 값의범위(구간추정)를 추정하는 알고리즘으로 설명력을 보유

- 대부분의 기계학습 알고리즘은 통계분포에 기반하지 않기 때문에 점추정 알고리즘

- 값의범위 정확성을 담보하진 않지만, 점추정 보다 다양한 해석을 가능하게 함

- 정확성 vs. 설명력 반비례 관계 존재


"통계추론, 기계학습 및 딥러닝의 흐름에 시간패턴을 반영하려 진화"

"지도학습(예측 분류), 비지도학습 문제에 모두 활용되는 필수 알고리즘"

"미래 예측을 포함한 추천 서비스와 같은 비즈니스에 활용중"

<img src='./img/TS_Evolution.png'>

#### 1) 통계추론(Statistical Inference) 알고리즘: 통계분포에 기반한 설명력 중시 알고리즘

<img src='./img/TS_Algorithm_Concept.png' width=600>

**(1) 단변량 선형기반**: Y가 1개 & Y와 X의 관계를 선형 가정

- Linear Regression

- ARIMA(AutoRegressive Integrated Moving Average)

- ARIMAX

- SARIMAX

**(2) 다변량 선형기반**: Y가 2개 이상 & Y와 X의 관계를 선형 가정

- Bayesian-based Models

- Vector Autoregression(VAR)

- Vector Error Correction Model(VECM)

**(3) 비선형기반**: Y와 X의 관계를 비선형 가정

- Exponential Smoothing

- ETS(Error/Trend/Seasonal)

- Kalman Filter

- State Space Model

- Change Point Detection(CPD)

- Autoregressive conditional heteroskedasticity(ARCH)

- Generalized Autoregressive Conditional Heteroskedasticity(GARCH)

#### 2) 기계학습/딥러닝 알고리즘: 컴퓨팅 기반 인공지능 알고리즘으로 정확성 높은 비선형 관계 추론

- Prophet

- Neural Prophet

- RNN(Recurrent Neural Network)

- LSTM(Long Short-Term Memory)

- GRU(Gated Recurrent Unit)

- Neural Networks Autoregression(NNAR)

- Attention

- Self-attention

- Transformer

#### 3) Platforms: 글로벌 기업들이 독자적으로 개발한 시계열 분석 플랫폼 확대중

- [Amazon Forecast](https://aws.amazon.com/ko/forecast/)

- [Automated ML Time-series Forecasting at Microsoft Azure](https://azure.microsoft.com/en-us/blog/build-more-accurate-forecasts-with-new-capabilities-in-automated-machine-learning/)

- [Time Series Forecasting with Google Cloud AI Platform](https://codelabs.developers.google.com/codelabs/time-series-forecasting-with-cloud-ai-platform#0)


### [정상성(Stationarity Process)](https://en.wikipedia.org/wiki/Stationary_process)

<img src='./img/DataAnalysis_CycleTS2.png'>

#### 0) 배경: 시계열 데이터를 활용한 분석에서는 새로운 가정 필요

| **데이터 방향** | **현실 가정** |
| :------: | :-------: |
| 시간 무관 일반적 데이터 | 모든 데이터 샘플들이 동일 분포에서 독립적으로 생성 <br> $\rightarrow$ Independent and Identically Distributed (i.i.d.) |
| 시간 관련 시계열 데이터 | i.i.d.가정 할 수 없고 현실문제를 단순화 한 새로운 가정 필요 <br> $\rightarrow$ 시간이 흘러도 통계적/확률적 성질이 변하지 않는다는 정상성(Stationary) |

- 새로운 가정 하에서, 정상성/비정상성 자체를 라벨로 활용하여 분류 지도학습 및 군집 비지도학습에도 활용

#### 1) 정상성의 의미 : 시간이 흘러도 통계적 특성(Statistical Properties)이 변하지 않고 일정

- **통계적 특성(Statistical Properties)**: 주로 평균(Mean)과 분산(Variance)/공분산(Covariance)를 의미하지만, 가장 보수적으로는 이를 포함한 모든 분포적 특성을 포함

- [Homoscedasticity](https://en.wikipedia.org/wiki/Homoscedasticity_and_heteroscedasticity) : 분산이 일정한(유한한, 발산하지않는) 경우를 의미

- [Heteroscedasticity](https://en.wikipedia.org/wiki/Homoscedasticity_and_heteroscedasticity) : 분산이 발산하는 경우를 의미

<img src='./img/Stationary(on).png' width=250>

<img src='./img/Stationary(non).png' width=600>

#### 2) 정상성의 종류

- 변수 :

$$X=\{X_1, X_2, ..., X_n\}$$

- 확률과정 :

$$Y={..., Y_{-2}, Y_{-1}, Y_0, Y_1, Y_2, ...}\\ X_1={..., X_{1, -2}, X_{1, -1}, X_{1, 0}, X_{1,1}, X_{1, 2}, ...}\\ X_2={..., X_{2, -2}, X_{2, -1}, X_{2,0}, X_{2, 1}, X_{2,2}, ...}$$

**(1) 약정상(Weak Stationarity, Wide-sense Stationary Process)**

(비수학적 이해)

1. $..., X_{i,-1}, X_{1,0}, X_{i,1}...$ 변수의 각 시계열 샘플들은 동일 분포이며,

2. $..., (X_{i,-3}, X_{i,-1}), (X_{i,-2}, X_{i,0}), (X_{i,-1}),X_{i,1})...$ 임의간격 샘플 2개씩의 묶음도 동일 분포

(수학적 이해)

1. $E(X_{it})=\mu$, for all time $t$ (The first moment estimation)

2. $Var(X_{it})=E(X_{it}^2)-E(X_{it})^2<\infty$, for all time $t$ (The second moment estimation)

3. $Cov(X_{is}, X_{ik})=Cov(X_{1(s+h)},X_{i(k+h)})=f(h)$, for all time $s,k,h$ (the cross moment estimation) $\Rightarrow$ Covariance just depends on $h$.

**(2) 강정상(Strong Stationarity, Strictly Stationary Process)**

"확률과정의 모든 분포 모멘트(Moment)가 시간 차이에만 의존하는 것(절대시간 미의존)"

(비수학적 이해)

1. $..., X_{i,-1}, X_{i,0}, X_{i,1},... 변수의 각 시계열 샘플들은 동일 분포이며,

2. $..., (X_{i,-3}, X_{i, -1}), (X_{i,-2}, X_{i,0}), (X_{i,-1}, X_{i,1}),...$ 임의간격 샘플 2개씩의 묶음도 동일 분포

3. $..., (X_{i,-5}, X_{i,-3}, X_{i, -1}), (X_{i,-2}, X_{i,0}, X_{i, 2}), (X_{i,-1}, X_{i,1}, X_{i, 3}),...$ 임의간격 샘플 3개씩의 묶음도 동일 분포

4. $(X_{i,-\infty},..., X_{i,-1}, X_{i,1}, X_{i,3}, ..., X_{i, \infty})$ 모든 시간 변화에도 동일 분포

**(3) 강정상과 약정상의 관계: 강정상** $\Rightarrow$ 약정상, but 약정상 $\nRightarrow$ 강정상

강정상 ${x_{it}}_{t=-\infty}^{t=+\infty}$의 특정 샘플 ${x_{it}}_{t=i_1}^{t=i_2}$의 평균과 분산까지만 일정한 약정상 일 수 있다.

약정상 ${x_{}it}_{t=-\infty}^{t=+\infty}$이 3차 이상의 통계적 특성인 모멘텀(Skewness, Kurtosis)에서도 일정하면 강정상이다.

#### 3) 백색잡음(White Noise, $WN$)

- 강정상의 대표예시로 시계열분석 기본알고리즘 중 가장 중요함

<img src='./img/White_Noise.png' width=500>

(1) 잔차들은 정규분포이고, (unbiased) 평균 0과 일정한 분산을 가져야 함

$${\epsilon_t : t = ..., -2, -1, 0, 1, 2,...}~N(0,\sigma_{\epsilon_t}^2)$$
$$\text{where } \epsilon_t \sim i,i,d \text{(independent and identically distributed)}$$
$$\epsilon_t=Y_i-\bar{Y}_i$$
$$E(\epsilon_t)=0$$
$$Var(\epsilon_t)=\sigma_{\epsilon_t}^2$$
$$Cov(\epsilon_s,\epsilon_k)=0 \text{ for different times! }(s \ne k)$$

(2) 잔차들이 시간의 흐름에 따라 상관성이 없어야 함 : 자기상관함수(Autocorrelation function, ACF) =0 확인

- 공분산(Covariance) : $Cov(Y_s, Y_k)=E[(Y_s-E(Y_s))(Y_k-E(Y_k))]=\gamma_{s,k}$

- 자기상관함수(Autocorrelation Function)

$$Corr(Y_s, Y_k)=\frac{Cov(Y_s, Y_k)}{\sqrt{Var(Y_s)Var(Y_k)}}=\frac{\gamma_{s,k}}{\sqrt{\gamma_s\gamma_k}}$$

- 편자기상관함수(Partial Autocorrelation Function): $s$와 $k$사이의 상관성을 제거한 자기상관함수
$$Corr[(Y_s-\hat{Y},Y_{s-t}-\hat{Y_{s-t}})] \text{ for } \$1$$

#### 4) 비정상 확률과정 (Non-stationary Process)

- 추세가 있어서 평균인 일차 모멘트($E(y_t)$)가 0이 아니며 시간에 따라 변함

- 추세가 없지만($E(y_t)=0$) 분산인 이차 모멘트($Var(y_t)$)가 시간에 따라 변함

    - 랜덤 워크(Random Walk): 비정상(Non-stationary) 대표예시로 차분시 백색잡음으로 변경

    $$Y_{it} = Y_{it-1}+\epsilon_t$$
    $$Y_{it}-Y_{it-1}=\epsilon_t$$
    $$\epsilon_t\sim N(0, \sigma_{\epsilon_t}^2)$$

<img src='./img/Random_Walk.png' width=400>

#### 6) 정리

| **예시** | **데이터** |
|:-----:|:-----:|
| 비정상 | 백색잡음(White Noise) |
| 비정상성 | 랜덤워크(Random Walk |

- 활용주요목적

    1) 모델링: 시계열 모형은 데이터가 Stationary라 가정 $\rightattow$ Stationary여야 예측 성능 높다

    2) 잔차진단: 백색잡음 또한 Stationary $\rightarrow$ 잔차도 Stationary여야 예측 성능 높다

- 활용단어예시

    - Stationary Process: 정상성인 시계열 데이터셋(프로세스)

    - Stationary Model: 정상성인 시계열데이터를 설명하는 모델

    - Trend Stationary: 트랜드를 제거하면 정상성인 시계열데이터

    - Seasonal Stationary: 계절성을 제거하면 정상성인 시계열데이터

    - Difference Stationary: 차분하면 정상성인 시계열데이터

### [정상성 테스트(Stationarity Test)](https://en.wikipedia.org/wiki/Unit_root_test)

#### 1) 기초통계 테스트(by Summary Statistics)

- 특정 시간(ex. 계절)에 따라 통계량이 일정한지 파악하여 정상성 확인

#### 2) 시각화 테스트(by Visual)

- 추세와 계절성이 없는지 파악하여 정상성 확인

<img src='./img/Stationary_Visual.png' width=500>

- **자기상관함수(Autocorrelation Function)**: 시차변화에 따른 자기상관을 의미

    $$Corr(Y_{s},Y_k)=\frac{Cov(Y_s, Y_k)}{\sqrt{Var(Y_s)Var(Y_k)}}=\frac{\gamma_{s,k}}{\sqrt{\gamma_s\gamma_k}}$$

    - 만약 데이터가 정상시계열이면, ACF 그래프가 모든 시차에서 0에 수렴하고,

    - 비정상시계열이면, ACF 그래프가 천천히 감소하거나 큰 양의 값

<img src='./img/Stationary_ACFComparison.png'>

#### 3) 통계량 테스트(by Statistics Test)

- 정상성 테스트 통계량으로 정상성 확인

- ["In statistics, a unit root test tests whether a time series variable is non-stationary and possesses a unit root."](https://en.wikipedia.org/wiki/Unit_root_test)

- [Augmented Dickey-Fuller(ADF) test](https://en.wikipedia.org/wiki/Augmented_Dickey–Fuller_test) : 주로 추세제거에 효과

**(1) 가설확인**

| 종류 | 해석 |
|:---:|:---:|
|**대중주장(귀무가설, Null Hypothesis)** | 데이터는 단위근(unit root) 있다. / 비정상 상태 / 시간의존 구조 |
|**나의주장(대립가설, Alternative Hypothesis)** | 데이터는 단위근 없다 / 정상 상태 / 시간의존 구조 아니다 |

**(2) 유의수준 설정 및 유의확률 확인**

- 유의수준: 5% (0.05) 분석가가 알아서 결정

- 유의확률(p-value): 컴퓨터가 알아서 추정

**(3) 의사결정**

|**기준**|**의사결정**|**해석**|
|:---:|:---:|:---:|
|**p-value>=유의수준(ex. 0.05)**| 대중주장 참 | 내가 수집/분석한 데이터는 단위근이 있다 / 비정상 상태 / 시간의존 구도 |
|**p-value<유의수준(ex. 0.05)** | 나의주장 참 | 내가 수집/분석한 데이터는 단위근이 없다 / 정상 상태 / 시간 의존 구도 아니다 |

- [ADF-GLS test](https://en.wikipedia.org/wiki/ADF-GLS_test)

    - 가설확인 : ADF와 동일

- [Phillips-Perron(PP) test](https://en.wikipedia.org/wiki/Phillips–Perron_test)

    - 가설확인 : ADF와 동일

- [Kwiatkowski Phillips Schmidt Shin(KPSS) test](https://en.wikipedia.org/wiki/Phillips–Perron_test)

    - 주로 계절성제거에 효과
    
    - 가설확인 : ADF와 반대

### 정상성 이해실습

In [1]:
# 라이브러리 호출
import pandas as pd
import numpy as np
import statsmodels.api as sm
from random import seed, random
import matplotlib.pyplot as plt
%reload_ext autoreload
%autoreload 2
# from module_timeseries import stationarity_adf_test, stationarity_kpss_test

# 랜덤워크 데이터 생성 및 통계량 test (rho=0)
plt.figure(figsize=(10, 4))
seed(1)
rho = 0
random_walk = [-1 if random() < 0.5 else 1]
for i in range(1, 1000):
    white_noise = -1 if random() < 0.5 else 1
    value = rho * random_walk[i-1] + white_noise
    random_walk.append(value)
plt.plot(random_walk)
# plt.title('Rho : {}\n ADF p-value : {}'.format(rho, np.ravel(stationarity_adf_test(random_walk, []))[1]))
